### ISSUE TITLE
f1 with insertPlate

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#100]
I am experiencing problems adding a surface tally which is using a surface of `insertPlate` object, but the same tally with surfaces of "standard" objects works fine:

This line works fine:
`./maxiv -r -defaultConfig Single BALDER  -OAdd plate object BalderRingCaveA  0 'Vec3D(0,0,0)' 100 100 100 Copper -T surface object BalderRingCaveA -1  AA`
but this one crashes:
`./maxiv -r -defaultConfig Single BALDER  -OAdd plate object BalderRingCaveA  0 'Vec3D(0,0,0)' 100 100 100 Copper -T surface object insertPlate0 -1  AA`

At the same time f4 works fine with `insertPlate0`:
`./maxiv -r -defaultConfig Single BALDER  -OAdd plate object BalderRingCaveA  0 'Vec3D(0,0,0)' 100 100 100 Copper -T flux p -1 insertPlate0  AA`

PS: this was tested with the master branch from 4 Feb 2019 (a44b56a). I could not do it with the most recent code due to issue #99

**Comment by SAnsell** [comment]
This has been fixed now  -- some issues remain but there are performance based I think. I copied the commit entry below. The error came about because of the work to implement separate simulations models (i.e. to get rid of the idea that Simulation is a singleton). My fault - so thanks!

**Commit f0aa02a7335e4d8 :** 

    Fixed insert objects to be first class obejcts.
    
       Insert objects need to be second class objects during construction
       so that a loop of A insert B insert A can't exist but need to
       be first class objects later (for tallies etc).
    
       They are now inserted into the objectGroup of the simulatoin from
       the key in ObjectRegister at construction.
       Surface linkage is added to the ObjectSurfMap (along with population)
       after full build and insert.
    
       Note we still havent filled the update that is needed to the OSM when
       an insert object completely splits an object, this leaves a dangling
       link in the OSM e.g. object A connect to B via surface X. Add an
       insert Object so that A does not connect to B via X (because I is in the
       way) and the connection is not removed or flagged for update.

**Comment by kbat** [comment]
thanks
