### ISSUE TITLE
f6 tally

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#27]
Hi Stuart,

Can you please give an example of the syntax of the heat tally. Say, I would like to calculate heat in all  (or some specific) cells of LowBeRef... I am studying the code of heatConstruct::processHeat, but do not quite understand how it works. What are cellRange and ANumber / BNumber?

Konstantin

**Comment by SAnsell** [comment]
Hi All,

  The old system of heat tallies worked -- but on reflection was not that clear. I have updated things in the master branch to improve things. So heat tallies should now be done with the following construct
  -T heat particle matNumber object 

The first "-T heat" is manditory. It indicates that your want a heat (f6) tally.
particle : this can be any mcnp particle or + if you want to do a +f6 tally.

mat number : this is a designator that says the material number [SEE BELOW] of cells that you wish to tally. It can be negative to mean all cells that are non-zero. And further can be zero to indicate that you tally the voids [note this only works successfully for tallying shortlived particles]

object : is the object name OR the cell nubmer range (e.g. 1 10000 ). That need to be tallied.

Consider the example:

t1Real -E Bulk -T heat n 5 WaterMod -r AA

Thiat will give a f6 tally on the aluminium [material 5] on the water moderator for the ISIS TS1 real model.  

I intend to improve the code to allow material names to be input.



Consider the following real exampe

\t
