### ISSUE TITLE
setVariable::PhotonVariables(FuncDataBase&)

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#28]
I get the following error while trying to compile the most recent code with g++:
`photonMod.cxx:121: undefined reference to `setVariable::PhotonVariables(FuncDataBase&)`

**Comment by SAnsell** [comment]
Ok my fault -- you need the new getMk.pl as PhotonVariables is a test project. If you have the last
version, please do a new ./getMk.pl before recompiling.

**Comment by kbat** [comment]
I see - you removed photonMod from @masterprog. I also did the same to compile at least the .so files.
Now it works. Thank you.
