### ISSUE TITLE
Intersection of Wheel and GuideBay4

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#33]
There is a geometrical error in kbatMerge:
![gb4](https://cloud.githubusercontent.com/assets/6359326/9468778/b2cac196-4b43-11e5-9977-7c00d1aa733d.png)

I have fixed it by [this commit](https://github.com/SAnsell/CombLayer/commit/029b12abbd7f7ebc008d223de7df986bcd2c9939) in the ButterflyEngineering branch . Please check if it's correct.

**Comment by SAnsell** [comment]
Fixed in branch VOR. Will put merged with mainline - However, I have done it by changing the variables so that the intersection doesn't happen.
