### ISSUE TITLE
Problems to compile master

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#35]
I get these error messages with trying to compile the latest master branch:

./CMake.pl
cmake ./
make ess
....

[ 55%] Building CXX object CMakeFiles/libpoly.dir/System/poly/PolyVar.cxx.o
/home/kbat/misc/soft/comblayer/150525/System/weights/weightManager.cxx:92:16: error: return type of out-of-line definition of
      'WeightSystem::weightManager::getWWG' differs from that in the declaration
weightManager::getWWG()
               ^
/home/kbat/misc/soft/comblayer/150525/System/weightsInc/weightManager.h:62:15: note: previous declaration is here
  WeightMesh* getWWG();
  ~~~~~~~~~~~ ^
/home/kbat/misc/soft/comblayer/150525/System/weights/weightManager.cxx:100:16: error: allocation of incomplete type
      'WeightSystem::WWG'
    WWGPtr=new WWG;
               ^~~
/home/kbat/misc/soft/comblayer/150525/System/weightsInc/weightManager.h:31:9: note: forward declaration of 'WeightSystem::WWG'
  class WWG;
        ^
/home/kbat/misc/soft/comblayer/150525/System/weights/weightManager.cxx:201:13: error: member access into incomplete type
      'WeightSystem::WWG'
      WWGPtr->write(OX);
            ^
/home/kbat/misc/soft/comblayer/150525/System/weightsInc/weightManager.h:31:9: note: forward declaration of 'WeightSystem::WWG'
  class WWG;
        ^
/home/kbat/misc/soft/comblayer/150525/System/weights/weightManager.cxx:202:13: error: member access into incomplete type
      'WeightSystem::WWG'
      WWGPtr->writeWWINP();
            ^
/home/kbat/misc/soft/comblayer/150525/System/weightsInc/weightManager.h:31:9: note: forward declaration of 'WeightSystem::WWG'
  class WWG;
        ^
4 errors generated.

**Comment by milocco** [comment]
In these days I am struggling for using the CombLayer CMake.pl script in
the Cygwin shell for Windows. It does not work, always breaks in the
link step. Did anyone of you never tried that?

Cheers,

Alberto

**Comment by kbat** [comment]
I have never tried compiling on cygwin... and I would never dare to do it :)
Now the code compiles, so I am closing the issue.
