### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#37]
Why do we include CMakeLists.txt in version control?
It is a generated file, and the inconvenient thing is that you have to stash it or check it out every time you want to change a branch.
So, I suggest to remove it from git.

**Comment by SAnsell** [comment]
Not 100% sure -- CMakeLists.txt is a standard file in every cmake project. It is human readable. It allows someone downloading the project to see what is going to be built. I change it from time to time to just compile one thing or run a profiler etc. 

   That I can generate it with a ./CMake.pl command is fine but a first timer that comes to the project would automatically type ./cmake ; make ; make install.. and find it works.

   I am close to agreeing with you but.... CMake.pl is too much junk (and my linux distribution based) to necessarily run on say redhat/debian but CMakeLists.txt is much more distribution safe.

**Comment by kbat** [comment]
Removed from the git index in 3bee1f91f
