### ISSUE TITLE
essDB

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#38]
I suggest to replace the `-essDB` flag with `-materials` followed by the material database name as implemented in 0da5cba.

This would allow users to create their own material database and choose which one to use by means of a command line argument.

Currently the default database is yours (I call it _shielding_, so the argument used by default is `-materials shielding`) with a possibility to use my definition (by calling `-materials neutronics`).

If you think it's a good idea, you can cherry-pick the commit 0da5cba from ButterflyEngineering.

**Comment by SAnsell** [comment]
I have cherry-picked the commit BUT the command line options materials is/was in used as at command line option to change the material in a cell/object etc. Thus by re-defining it, the normal case has been effectively masked. So I have changed the name to matDB. 

Now you should do -matDB neutronics or -matDB help (to list options).
