### ISSUE TITLE
can't compile master

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#61]
Hi Stuart,

I can't compile the current master branch. cmake has problems with the linac target:

```FINISH CMake.pl
-- Configuring done
CMake Error at CMakeLists.txt:641 (add_executable):
  Cannot find source file:

    master/Main/linac

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: linac
CMake Error: Cannot determine link language for target "linac".
-- Generating done```

**Comment by SAnsell** [comment]
The project added the linac target -- this normally means that you need a
new linac.cxx

I forgot to add this to the project -- so I have added it now [sorry].

You will need to do a new ./CMake.pl -O etc...

Stuart.
