### ISSUE TITLE
problems with 2 mesh tallies

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#71]
I tried to insert 2 mesh tallies and found 3 problems:

This command
>./ess -r -T tmesh DOSE free 'Vec3D(-285,4800,-150)' 'Vec3D(315, 16300, 200)' 5 80 5 -T tmesh DOSEPHOTON free 'Vec3D(-285,4800,-150)' 'Vec3D(315, 16300, 200)' 5 80 5 a

gives two meshes:

> tmesh
rmesh1:n DOSE 1
mshmf1 1e-09 0.0111 1e-08 0.0128 2.5e-08 0.0144 1e-07 0.0187 2e-07
  ...
        800 2.24 900 2.3 1000 2.35 2000 2.76 5000 3.64 10000 4.75
cora1 -285 4i 315
corb1 4800 79i 16300
corc1 -150 4i 200
endmd
tmesh
rmesh1:n DOSE 1
mshmf1 0.01 0.000247 0.015 0.000562 0.02 0.00081 0.03 0.00113 0.04
..
        5000 0.904 6000 0.929 8000 0.965 10000 0.994
cora11 -285 4i 315
corb11 4800 79i 16300
corc11 -150 4i 200
endmd

1. There should not be `endmd/tmesh` lines between the meshes.
2. The `mshmf` numbering is wrong. I think it should be
>rmesh1:n DOSE 1
mshmf1
rmesh1:n DOSE 2
mshmf2
3. If I insert, say, a f4 tally, it goes between the two meshes (i.e. inside tmesh/endmd block), while it should be placed either before or after.

**Comment by SAnsell** [comment]
Sorry -- this is my fault : 

It has been half fixed in commit 4a21e3. [Hopefully] 
The endmd and tmesh parts have been fixed, along with the order of the tallies in the output.
-- the next checking should fix the next part with mshmf.

 Many thanks for the long bug report.

**Comment by SAnsell** [comment]
Ok fixed the mshmf index error. 

But it is an ugly fix and I will tidy it up later I think.

**Comment by kbat** [comment]
Thanks - now it works correct.
