### ISSUE TITLE
Mixtures with Void

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#84]
Before I forget: I observe the mixtures with Void have density of original material. Example:

> ./ess -r -v ` H2O AA
> ./ess -r -v TopPreModMat1x0 H2O%Void%80.0 BB

then diff AA1.x and BB1.x show that densities of `TopPreModMat1x0` are the same.

**Comment by SAnsell** [comment]
I think this is fixed [hopefully] -- thx

**Comment by kbat** [comment]
Confirm that it's fixed. Thank you!
