### ISSUE TITLE
Cell renumbering

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#93]
Cell renumbering for a specific object is broken in the current master branch.
For example, both `./ess -r AA` and `./ess AA` work fine, but
> ./ess -r BeRef AA

generates
> EXCEPTION FAILURE :: InContainerError<>::                                      $
> New cell not found                                                             $
> key== 1000002 == 
> Code Stack:                                                                    $
> ::main                                                                         $
>  MainProcess[F]::buildFullSimulation                                          $
>    SimImportance[F]::importanceSim                                            $
>      SimImportance[F]::importanceSim(MCNP)                                    $
>        MainProcess::renumberCells                                             $
>          SimMCNP::renumberCells                                               $
>            PhysicsCards::substituteCell                                       $
>              PhysImp::renumberCell 
> Undeleted memory                                                               $
> Obj Ox2977e80 :: Rule ++ Simulation::addCell(int,Qhull)                        $
> Name == 0

**Comment by SAnsell** [comment]
Sorry that is my fault [again!!]

   Fix coming soon

**Comment by SAnsell** [comment]
Bug Fixed:  minor error overlapping values in Simulation::renumberCells.

**Comment by SAnsell** [comment]
Think this is now fixed with the fluka output. I believe that is correctly fixes the problem with the cells and tallys and physics. -- if this doesn't work for you please let me know.
