### ISSUE TITLE
ShutterUnitGenerator.h

### ISSUE THREAD

**Issue by kbat** [SAnsell/CombLayer#99]
Hello,

The current master branch can not be compiled since `ShutterUnitGenerator.h` is missing.

Konstantin

**Comment by SAnsell** [comment]
Added -- sorry for the stupidity.

**Comment by kbat** [comment]
You have added .cxx, but the .h file is still missing.

**Comment by SAnsell** [comment]
On day I might actually test stuff.... 
  I think this now works.
